### ISSUE TITLE
Getting Error in clmtools

### ISSUE THREAD

**Issue by muhammad-anwaar** [auduno/clmtools#10]
I want to use clmtools to train the model with existing data , but The clmtool not working.
its giving this error.
Can you please help regarding this issue.

getting negative examples from landscape images
C:\Users\anwaar\Anaconda2\lib\site-packages\sklearn\preprocessing\data.py:160: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
C:\Users\anwaar\Anaconda2\lib\site-packages\sklearn\preprocessing\data.py:177: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0.
  warnings.warn("Numerical issues were encountered "
training patch:0
0
C:\Users\anwaar\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\anwaar\Anaconda2\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Traceback (most recent call last):
  File "pdm_builder.py", line 54, in <module>
    patchModel = build_patches(data_patches, gradient=True, lbp=True, weights=weights, optimize_params=True)
  File "c:\clm\clmtools\pdm_builder\buildlib\buildpatch.py", line 169, in build_patches
    clfg = GridSearchCV(SVR(kernel="linear"), {'C':[0.1], 'epsilon' : [0.4, 0.3, 0.2, 0.1]}, loss_func=mean_squared_error, verbose=100)
TypeError: __init__() got an unexpected keyword argument 'loss_func'

**Comment by imadbakir** [comment]
Same !

**Comment by tkomde** [comment]
Some arguments in scikit-learn function are deprecated. Comment out "lossfunc = ..." of GridSearchCV in buildpatch.py will help you.
Old ref.
http://scikit-learn.org/0.15/modules/generated/sklearn.grid_search.GridSearchCV.html
New ref.
http://scikit-learn.org/0.19/modules/generated/sklearn.grid_search.GridSearchCV.html
